pipeline{
	agent any
	
	stages{
		stage('clean'){
			steps{
				echo "Hello World from pipelines"
				}
			}
		}
	
		stage('test'){
			steps{
				echo "Hello World from pipelines"
				}
			}
		}

		stage('package'){
			steps{
				echo "Hello World from pipelines"
				}
			}
		}
}
